// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtrgb4vMssggwMNY4rF90L6TX1K9So2RU',
    appId: '1:962598338935:web:237ed79674671d73532172',
    messagingSenderId: '962598338935',
    projectId: 'real-time-chat-ad78a',
    authDomain: 'real-time-chat-ad78a.firebaseapp.com',
    storageBucket: 'real-time-chat-ad78a.appspot.com',
    measurementId: 'G-PF9XH7L9WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBEtSlZYj9E0M0-f6DTWT3F9vmaO4qAt0',
    appId: '1:962598338935:android:74a784c74ba7ca8d532172',
    messagingSenderId: '962598338935',
    projectId: 'real-time-chat-ad78a',
    storageBucket: 'real-time-chat-ad78a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6_7LX6i38QLNVXa1Hx-i403u8B52BA6Y',
    appId: '1:962598338935:ios:b1bde43d9f697f4c532172',
    messagingSenderId: '962598338935',
    projectId: 'real-time-chat-ad78a',
    storageBucket: 'real-time-chat-ad78a.appspot.com',
    iosBundleId: 'com.realtimechat.realtimechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6_7LX6i38QLNVXa1Hx-i403u8B52BA6Y',
    appId: '1:962598338935:ios:b1bde43d9f697f4c532172',
    messagingSenderId: '962598338935',
    projectId: 'real-time-chat-ad78a',
    storageBucket: 'real-time-chat-ad78a.appspot.com',
    iosBundleId: 'com.realtimechat.realtimechat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtrgb4vMssggwMNY4rF90L6TX1K9So2RU',
    appId: '1:962598338935:web:68c2537f22c2bebd532172',
    messagingSenderId: '962598338935',
    projectId: 'real-time-chat-ad78a',
    authDomain: 'real-time-chat-ad78a.firebaseapp.com',
    storageBucket: 'real-time-chat-ad78a.appspot.com',
    measurementId: 'G-TC253LMQ8P',
  );
}
